language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -p 'test.py'
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: beautyrest